### ISSUE TITLE
Electronics instructions could use more pictures

### ISSUE THREAD

**Issue by jklingen92** [AstroPlant/Casing#10]
I'm attempting to build the electronics panel and I made a mistake that will set me back some amount of time. I connected the ferrule tipped power supply wires into the power supply and they wouldn't come out. While trying to remove them, I instead remove the connector from the panel. I think with more pictures of the wires and the connectors they are going to, I might not have made this mistake.

![IMG_20200627_191551~2](https://user-images.githubusercontent.com/8923518/85934020-7203ee00-b8ab-11ea-9048-b3492b03a772.jpg)
![IMG_20200627_191636](https://user-images.githubusercontent.com/8923518/85934021-729c8480-b8ab-11ea-946f-2896945e6a93.jpg)
![IMG_20200627_191653](https://user-images.githubusercontent.com/8923518/85934022-73cdb180-b8ab-11ea-878b-ca241bccbf39.jpg)

Does anyone have any recommendations for how I can solve this? I may be able to access an electronic shop but I'm not sure.

**Comment by SidneyNiccolson** [comment]
Hi Jake,

Very unfortunate to hear that the connector came loose. 

The connector is a: wago 2060 402 [more info](https://www.tme.eu/en/details/2060-402_0998-404/led-connectors/wago/2060-402-998-404/). I'm not an electronics expert, but you could either 1) try to remove the cable or if that doesn't work 2) order the component from an electronics shop. You might have to look at larger suppliers like TME, DigiKey or Mouser. 
Once you managed the above, you'll need to re-solder the component back on the board. Officially this is done with "reflow soldering". 

For the Wago component, the only wires that fit are the bare-metal ones. Do you have access to gitbook? If not, I still have access I believe and could add a picture there next to the remark. 

I hope this helps!

**Comment by jklingen92** [comment]
I haven't used gitbook before so I'm not sure if I can edit or not.

**Comment by thiemehennis** [comment]
please share the emailaddress you want to use for Gitbook here so I can add
you as a writer.


--
Thieme Hennis PhD // +31651855220 // Amsterdam, Den Haag

**Comment by jklingen92** [comment]
jklingen92@gmail.com

**Comment by SidneyNiccolson** [comment]
@jklingen92 
I was wondering how to progress with fixing the broken part went? Additionally do you have access now? 

I updated the gitbook with a simple picture to let people now which cables to use. Feel free to update it with nicer pictures or texts.

**Comment by SidneyNiccolson** [comment]
Hi @jklingen92 ,

I'm closing this issue now as it is stale. If you want to re-open it, please ask it on Slack "Questions" channel and I'll re-open if necessary.

**Comment by jklingen92** [comment]
@SidneyNiccolson I was out of town, but I am resuming construction now. 

I do have access, and I was able to resolder the part. I haven't tested the connection, it was a tricky soldering job for a beginner, but I think that I got it on acceptably. The image on GitBook looks perfect. Thanks for that!
