### ISSUE TITLE
Not sure where +V1 5V from power supply should be connected

### ISSUE THREAD

**Issue by jklingen92** [AstroPlant/Casing#11]
The electronics assembly instructions don't seem to specify where the +V1 5V should be connected.Based on the wiring image and logic, I think should be connected to the extension board (although in the image, it is wiring along a different path from the 24V power cables for no obvious reason). If I'm missing some part of the instructions, please direct me, but I've looked over everything under the power supply heading (and searched the whole document - `+V1 only appears in the testing section).

**Comment by SidneyNiccolson** [comment]
@jklingen92 it is correct that the explanation was missing. I checked the other guide on "Electronics assembly from scratch" and that did contain the documentation. I think I forgot to add it in the "maker edition" guide (it is now added though). 

To answer your question, yes the +V1 should go to 5V on the extension board.  If you are going to power the RPi through the AC/DC converter make sure your jumper configuration is correct on the extension board. 

All the best, 

Sidney
